### ISSUE TITLE
Submissions Form

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#1]
# Goal
Update the submission form to have the following fields

### Wallet
Payout wallet should be altered to get 3 wallets instead of just one wallet
- wPOKT receiving address
- ARB receiving address
- OP receiving address 
### Impact category
Impact category should be selected from the below options, each project can select only of these
  - **Protocol:** recognising contributions to the POKT stack itself, either through contribution to main code sources such as Morse and Shannon, or through other dependencies and POKT- related repos.
  - **Ecosystem:** recognising tools and applications using or enhancing the experience of working with the POKT stack and may include wallets, explorers or other associated tech. It's all about making an impact on the broader POKT ecosystem through your creations.
  - **Adoption:** recognising activities that drove awareness and adoption of the POKT Network, whether through discussions, referrals, content or any other meaningful contribution.

## Fields to be added 
- Add a section for adding social media links such as Github, twitter, discord, telegram, ... 

# How
- Update the attestation schema to ensure capturing the correct information
- Update the website layout

**Comment by mehrdadmms** [comment]
# Feedback - April 24th, 2024

- [ ] User shouldn't be able to select multiple impact categories 
<img width="559" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/e8f60868-c2c7-48eb-8ab5-424774fd841b">

- [ ] Funding source is not required 
- [ ] When the page is like this and I click on "create application" the button doesn't do anything and the errors don't show
<img width="1059" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/6879df3a-fe3b-446c-8854-aa163053bb75">

- [ ] the placeholders are percieved as the actual value. the color should be different. here although it shows USD I get error because I have to type USD again. 
<img width="197" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/43c12993-c242-4bf7-a351-98f97e54627e">

**Comment by satiparpar** [comment]
- [ ] pocket icon is not available when you want to review an application.
![icon](https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/133249744/d2c03363-0b74-4221-96ea-4129eb24f8e5)

**Comment by satiparpar** [comment]
pocket icon is not available when you want to review an application.

![icon (2)](https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/133249744/e24de242-20f1-46ef-bead-5a367832a5e7)

**Comment by satiparpar** [comment]
- [ ] Here we only have 4 options but users can add many many rows ( there is no limit ). 

![Screenshot (29)](https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/133249744/0941fbce-0b81-4ee8-a9be-d7db920d4d7c)
