### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#84]
# Goal 
update read me

**Comment by ahmadyazdanii** [comment]
@mehrdadmms, Could you please share the production URL and commercial name for the project?

**Comment by mehrdadmms** [comment]
prod url: https://impact.pokt.network/
Name: Retroactive POKT Goods Funding
description: 
POKT’s experimental first round of retroactive grants is open to projects & individuals for contributions that delivered impact to the POKT ecosystem.
