### ISSUE TITLE
Add loading

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#97]
# Goal
When users click on projects it takes a long time (around 6 second to load the page), please put a loading that gives the users a sense that something is happening. 

# Task 
- [x] Add loading where users click on a project to see its details.

**Comment by mehrdadmms** [comment]
# Figma 
https://www.figma.com/design/x28TrzkBzDgJ5XNnE2zqnw/Design-file?t=lOtZLwUIPsjz5ZwL-0

**Comment by mhsamie** [comment]
sp:2
